image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
  USER_GITLAB: yogonza524
  APP_NAME: ms-fletz-people
  REPO: fletz-people

stages:
  - build
  - package

gradle-build:
  image: java:8-jdk
  stage: build
  script:
    - ./gradlew clean pmdMain pmdTest build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master

docker-build:
  stage: package
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
  - docker build -t registry.gitlab.com/yogonza524/$REPO .
  - docker push registry.gitlab.com/yogonza524/$REPO

